version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET='configuration-119178693678'
      - export DIRECTORY='Lambda-Functions/pipeline-artifacts/'
      - aws cloudformation package --template-file lambda/template.yml --s3-bucket $BUCKET --s3-prefix $DIRECTORY --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
